apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes:
    # ReadWriteOnce: the volume can be mounted as read-write by a single node
    # ReadWriteMany: the volume can be mounted as read-write by many nodes
    # ReadOnlyMany: the volume can be mounted read-only by many nodes
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi